version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Pgsq1p@ssword
      POSTGRES_USER: postgres
      POSTGRES_DB: matemagica
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports: 
      - 8080:8080