version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ti@cc
      POSTGRES_USER: ti2cc
      POSTGRES_DB: site_golpes
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports: 
      - 8080:8080